### PR TITLE
Una nova entrega ;-)

### PR DESCRIPTION
**Pull request by agustim**
No he provat mai això dels pull request :-)

### CODE REVIEW

**Comment by fgui** [comment]
es el primer cop que faig això!

francesc@cesc-T420:~/repos/meteor.js-book$ git pull
https://github.com/agustim/meteor.js-book master
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 16 (delta 2), reused 16 (delta 2)
Unpacking objects: 100% (16/16), done.
From https://github.com/agustim/meteor.js-book
- branch            master     -> FETCH_HEAD
  Merge made by the 'recursive' strategy.
  04/vote/.meteor/.gitignore |    1 +
  04/vote/.meteor/packages   |   10 ++++++++++
  04/vote/client/main.js     |   36 ++++++++++++++++++++++++++++++++++++
  04/vote/client/survey.css  |    8 ++++++++
  04/vote/client/survey.html |   32 ++++++++++++++++++++++++++++++++
  04/vote/model.js           |    2 ++
  04/vote/server/main.js     |   17 +++++++++++++++++
  04/vote/server/methods.js  |   14 ++++++++++++++
  index.cat.txt              |    4 ++--
  index.eng.txt              |    4 ++--
  10 files changed, 124 insertions(+), 4 deletions(-)
  create mode 100644 04/vote/.meteor/.gitignore
  create mode 100644 04/vote/.meteor/packages
  create mode 100644 04/vote/client/main.js
  create mode 100644 04/vote/client/survey.css
  create mode 100644 04/vote/client/survey.html
  create mode 100644 04/vote/model.js
  create mode 100644 04/vote/server/main.js
  create mode 100644 04/vote/server/methods.js
  francesc@cesc-T420:~/repos/meteor.js-book$

fet!

## 

Francesc Guillén
software crafter / entrepreneur
Contact info : https://norbt.com/francesc
Above all, if we don't spell properly, how can we possibly expect, our
lives to be magical?

**Comment by fgui** [comment]
si vols tb et puc enviar un pull request però no se si voldràs els canvis
que he fet :P. Crec que sols he canviat codi un != canviat a !==

## 

Francesc Guillén
software crafter / entrepreneur
Contact info : https://norbt.com/francesc
Above all, if we don't spell properly, how can we possibly expect, our
lives to be magical?

**Comment by fgui** [comment]
Una de les coses interessant del 01/chat és que pots parar el servidor i
fer missatges en local que al final s'envien. En canvi al la versió
02/chatlogin crec que es per l'habilitat de veure en local abans d'enviar
no se si es podria fer pq fos com el 01 mantenint la seguretat i
autentificació.

## 

Francesc Guillén
software crafter / entrepreneur
Contact info : https://norbt.com/francesc
Above all, if we don't spell properly, how can we possibly expect, our
lives to be magical?

**Comment by agustim** [comment]
Es clar que els vull!!!

2013/3/5 Francesc notifications@github.com

> si vols tb et puc enviar un pull request però no se si voldràs els canvis
> que he fet :P. Crec que sols he canviat codi un != canviat a !==
> 
> ## 
> 
> Francesc Guillén
> software crafter / entrepreneur
> Contact info : https://norbt.com/francesc
> Above all, if we don't spell properly, how can we possibly expect, our
> lives to be magical?
> 
> On Tue, Mar 5, 2013 at 10:24 AM, Francesc Guillen <
> francesc.guillen@gmail.com> wrote:
> 
> > es el primer cop que faig això!
> > 
> > francesc@cesc-T420:~/repos/meteor.js-book$ git pull
> > https://github.com/agustim/meteor.js-book master
> > remote: Counting objects: 19, done.
> > remote: Compressing objects: 100% (12/12), done.
> > remote: Total 16 (delta 2), reused 16 (delta 2)
> > Unpacking objects: 100% (16/16), done.
> > From https://github.com/agustim/meteor.js-book
> > - branch master -> FETCH_HEAD
> >   Merge made by the 'recursive' strategy.
> >   04/vote/.meteor/.gitignore | 1 +
> >   04/vote/.meteor/packages | 10 ++++++++++
> >   04/vote/client/main.js | 36 ++++++++++++++++++++++++++++++++++++
> >   04/vote/client/survey.css | 8 ++++++++
> >   04/vote/client/survey.html | 32 ++++++++++++++++++++++++++++++++
> >   04/vote/model.js | 2 ++
> >   04/vote/server/main.js | 17 +++++++++++++++++
> >   04/vote/server/methods.js | 14 ++++++++++++++
> >   index.cat.txt | 4 ++--
> >   index.eng.txt | 4 ++--
> >   10 files changed, 124 insertions(+), 4 deletions(-)
> >   create mode 100644 04/vote/.meteor/.gitignore
> >   create mode 100644 04/vote/.meteor/packages
> >   create mode 100644 04/vote/client/main.js
> >   create mode 100644 04/vote/client/survey.css
> >   create mode 100644 04/vote/client/survey.html
> >   create mode 100644 04/vote/model.js
> >   create mode 100644 04/vote/server/main.js
> >   create mode 100644 04/vote/server/methods.js
> >   francesc@cesc-T420:~/repos/meteor.js-book$
> > 
> > fet!
> > 
> > ## 
> > 
> > Francesc Guillén
> > software crafter / entrepreneur
> > Contact info : https://norbt.com/francesc
> > Above all, if we don't spell properly, how can we possibly expect, our
> > lives to be magical?
> > 
> > On Tue, Mar 5, 2013 at 4:00 AM, agusti moll notifications@github.comwrote:
> > 
> > > ## No he provat mai això dels pull request :-)
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/agustim/meteor.js-book master
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/srcordills/meteor.js-book/pull/1
> > > Commit Summary
> > > - charpet 04
> > > 
> > > File Changes
> > > - _A_ 04/vote/.meteor/.gitignore<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-0>(1)
> > > - _A_ 04/vote/.meteor/packages<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-1>(10)
> > > - _A_ 04/vote/client/main.js<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-2>(36)
> > > - _A_ 04/vote/client/survey.css<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-3>(8)
> > > - _A_ 04/vote/client/survey.html<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-4>(32)
> > > - _A_ 04/vote/model.js<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-5>(2)
> > > - _A_ 04/vote/server/main.js<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-6>(17)
> > > - _A_ 04/vote/server/methods.js<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-7>(14)
> > > - _M_ index.cat.txt<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-8>(4)
> > > - _M_ index.eng.txt<
> > >   https://github.com/srcordills/meteor.js-book/pull/1/files#diff-9>(4)
> > > 
> > > Patch Links:
> > > - https://github.com/srcordills/meteor.js-book/pull/1.patch
> > > - https://github.com/srcordills/meteor.js-book/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/srcordills/meteor.js-book/pull/1#issuecomment-14430699
> .

## 

https://norbt.com/2FTRJ9

**Pull request closed without merging**
